### ISSUE TITLE
[Request] Please add an option to sign in to websites :)

### ISSUE THREAD

**Issue by jxmesth** [Thomasedv/Grabber#13]

**Comment by Thomasedv** [comment]
Added the username option, and if it's checked, Grabber will ask you for a password when you start the download. The password will not be saved to disk, so you need to reenter after a restart. (Because saving passwords to disk is risky and careless)

It's just a quick test build, so not much bug testing, but give it a shot and see if it works for you. 
https://github.com/Thomasedv/Grabber/releases/tag/V4.3-alpha

**Comment by jxmesth** [comment]
> Added the username option, and if it's checked, Grabber will ask you for a password when you start the download. The password will not be saved to disk, so you need to reenter after a restart. (Because saving passwords to disk is risky and careless)
> 
> It's just a quick test build, so not much bug testing, but give it a shot and see if it works for you.
> https://github.com/Thomasedv/Grabber/releases/tag/V4.3-alpha

Thank you so much! 

I've just tried it and it seems to be working fine. The only thing that's kinda confusing is that when I enter a wrong password for my username the program just continues downloading the video without giving a warning or letting me know that it could not successfully log in. 

This could be an issue as some sites require users to be logged in and sometimes limit the download quality if the user is not logged in correctly. Thank you once again for your help :)

**Comment by Thomasedv** [comment]
Unfortunately, since this wraps youtube-dl, it's limited what i can do. I think it will stop if it can't download anything, but if youtube-dl doesn't stop itself it's out of my reach. I could make an option to reenter the password, but restarting is just as quick most of the time anyways. Could mark it down on the to do list, along with checking if youtube-dl ended with an error with the log-in and re-ask for password.

**Comment by jxmesth** [comment]
> Unfortunately, since this wraps youtube-dl, it's limited what i can do. I think it will stop if it can't download anything, but if youtube-dl doesn't stop itself it's out of my reach. I could make an option to reenter the password, but restarting is just as quick most of the time anyways. Could mark it down on the to do list, along with checking if youtube-dl ended with an error with the log-in and re-ask for password.

Sure thing, appreciate it.

**Comment by jxmesth** [comment]
Also, I was just wondering, since this is a wrapper for youtube-dl, would it be possible to have something like multiple connections to download from a website? Having multiple connections greatly improves the download speed especially on websites that throttle (Which most websites do).

**Comment by Thomasedv** [comment]
You mean parallel downloads basically? Yes, it's possible, since i just run the program with commands. I just haven't had a good way to actually express any progress inside the GUI. Having multiple programs report their process would completely mess up the way i deal with what youtube-dl output (the text). For now, queueing the downloads is your best bet. If you start another download, while the first is running, it will start the next one automatically afterwards.  

I've also noticed a bug which needs to be looked at regarding adding new options.

**Comment by jxmesth** [comment]
> You mean parallel downloads basically? Yes, it's possible, since i just run the program with commands. I just haven't had a good way to actually express any progress inside the GUI. Having multiple programs report their process would completely mess up the way i deal with what youtube-dl output (the text). For now, queueing the downloads is your best bet. If you start another download, while the first is running, it will start the next one automatically afterwards.
> 
> I've also noticed a bug which needs to be looked at regarding adding new options.

Alright, sweet! I think that fixes this issue and this can now be closed. Thank you for all your help.

Also, can I just say, Amazing work on making this program, it's awesome!! . This is literally the best and the easiest Youtube-dl GUI to use. Thank you so much :)
